In [1]:
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Question - 1
ans - 

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
type(list_[1])

str

In [7]:
array_list.dtype

dtype('<U1')

 The data type of the elements in the Python list list_ is <class 'str'>, which stands for string. The data type of the elements in the NumPy array array_list is <U1, which is a Unicode string of length 1. The difference arises from the fact that NumPy arrays have a fixed data type for their elements, and when creating the array, NumPy tries to infer the most appropriate data type based on the input data.

Question - 2
ans  - 

In [11]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(i.dtype)

<U1
<U1
<U1
<U1
<U1


Question - 3
ans - 

In [13]:
array_list = np.array(object = list_, dtype = int)

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [20]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


for i in array_list:
    print(i.dtype)

there is a difference between the type of elements of both the varibles, 
array_list contains integer as it is modified earlier and list_ contains string datatype.

Question - 4
ans - 

In [24]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [25]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.shape(num_array)

(2, 3)

In [27]:
np.size(num_array)

6

Question - 5
ans - 

In [31]:
 zero_matrix= np.zeros((3,3))

In [32]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Question - 6
ans -

In [34]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])